### ISSUE TITLE
Won't update WP if version is double digits (#.#) vs. triple (#.#.#)

### ISSUE THREAD

**Issue by ericrasch** [evolution/wordpress#26]
I couldn't update WP to version 4.0. When I tried, it downloaded 3.9.2 again. I think we discussed this a bit in the meetups.

![image](https://cloud.githubusercontent.com/assets/654858/4631953/ab343ca0-53b9-11e4-833f-9f7b63d71786.png)

**Comment by EvanK** [comment]
This is an issue with [github-latest](https://github.com/tmpvar/github-latest), which in turn uses [semver](https://github.com/npm/node-semver). I'll open an issue with the semver folks, but I doubt it will accomplish much, since a two digit version is not strictly speaking a semantic version

**Comment by ericclemmons** [comment]
Yea, I don't think it's a bug with semver, TBH.  I think it's WordPress breaking convention, and these libraries are presumptuous.

Perhaps it'd be better if `github-latest` _gracefully_ supported 2-digit versions?

Either that, or we make the Github API request ourselves & just sort, since that's pretty much what we're wanting...

**Comment by EvanK** [comment]
Related: npm/node-semver#19

**Comment by jimmynotjim** [comment]
They (being WordPress) [did it again](https://github.com/WordPress/WordPress/releases/tag/4.2) with 4.2 so it might be easier to just hit the api yourselves.

**Also HI!!!**
![f2a0cc7f1c74bdfbdd7ea96f5bd2800226ca723e5a5f8dd77b4070cffc58b0fb](https://cloud.githubusercontent.com/assets/1280430/7499960/b630ae4c-f3f8-11e4-94f0-5e7c80a601ca.jpg)
